apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
spec:
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - name: nodered
        image: nodered/node-red
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 1880
        volumeMounts:
         - name: nodered-volumeclaim
           mountPath: "/data"
      volumes:
      - name: nodered-volumeclaim
        persistentVolumeClaim:
          claimName: nodered-volumeclaim
